apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-ns-role
  namespace: sen-dev-dev-azr-k8s-sen-w2-001
rules:
- apiGroups: ["", "apps", "networking.k8s.io"]
  resources: ["deployments", "services", "configmaps", "secrets", "ingresses"]
  verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-ns-binding
  namespace: sen-dev-dev-azr-k8s-sen-w2-001
subjects:
- kind: ServiceAccount
  name: default
  namespace: flux-system
roleRef:
  kind: Role
  name: flux-ns-role
  apiGroup: rbac.authorization.k8s.io
